---
apiVersion: v1
kind: Secret
metadata:
  name:      pq-scaler-secret
  namespace: default
  labels:
    app: solace-pqdemo-subscriber
type: Opaque
stringData:
  SEMP_USER:         pq-demo-view
  SEMP_PASSWORD:     c306muq7bvp98fehhu4108a44n
  #SEMP_USER:         pq-demo-admin
  #SEMP_PASSWORD:     l6vvuc12s20b489r1h0mfj5ln8
## data:
##  SEMP_USER:         YWRtaW4=
##  SEMP_PASSWORD:     ZGVtb3Bhc3M=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pq-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter:   username
      name:        pq-scaler-secret
      key:         SEMP_USER
    - parameter:   password
      name:        pq-scaler-secret
      key:         SEMP_PASSWORD
